FROM node:latest
WORKDIR /front-end
ENV PATH="./front-end/node_modules/.bin:$PATH"

RUN mkdir -p node_modules/node-sass/vendor/linux-x64-51
RUN curl -L https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64-51_binding.node -o node_modules/node-sass/vendor/linux-x64-51/binding.node

COPY package.json ./
RUN npm install
RUN npm rebuild node-sass

COPY . .

CMD ["npm", "start"]